id: ICDCFCCCC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:57:06+00:00'
last_modified: '2022-06-08T11:00:36.823014+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29232
  title: གསུང་འབུམ། བསྟན་པ་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4C9D:
      image_group_id: I5250
      title: ''
      total_pages: 590
      order: 1
      base_file: 4C9D.txt
    '8258':
      image_group_id: I5251
      title: ''
      total_pages: 433
      order: 2
      base_file: 8258.txt
    6DAA:
      image_group_id: I5252
      title: ''
      total_pages: 524
      order: 3
      base_file: 6DAA.txt
    EC18:
      image_group_id: I5253
      title: ''
      total_pages: 446
      order: 4
      base_file: EC18.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
